"""First Migration

Revision ID: 1e0ee008062e
Revises: 
Create Date: 2020-09-19 12:13:35.049187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0ee008062e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servidor',
    sa.Column('ID_SERVIDOR', sa.Integer(), nullable=False),
    sa.Column('NOME', sa.String(length=50), nullable=True),
    sa.Column('SENHA', sa.String(length=10), nullable=True),
    sa.Column('SECRETARIA', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ID_SERVIDOR'),
    sa.UniqueConstraint('SENHA')
    )
    op.create_index(op.f('ix_servidor_ID_SERVIDOR'), 'servidor', ['ID_SERVIDOR'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servidor_ID_SERVIDOR'), table_name='servidor')
    op.drop_table('servidor')
    # ### end Alembic commands ###
